pull_request_rules:
  - name: controlled approved-source copy cp7d
    conditions:
      - label = h1-copy-approved-cp7d
      - base = main
      - "#approved-reviews-by >= 1"
    actions:
      copy:
        branches:
          - release
  - name: controlled generated-copy merge cp7d
    conditions:
      - author = mergify[bot]
      - base = release
      - label = h1-copy-merge-cp7d
    actions:
      merge:
        method: squash
